Repository Unilasalle-SmartCare/smartcare-docker, pull requests merged in 2022-07, with the labels that each got.

#12 Criação de rota de Cidade
  smartcare-compose/apis/web-api/web-api.py
  smartcare-compose/web/nginx/default.conf
Labels: melhoria

#14 Criação de rotas de Enfermidade e Paciente
  postman-collections/Cidade.postman_collection.json
  smartcare-compose/apis/web-api/web-api.py
  smartcare-compose/web/nginx/default.conf
Labels: melhoria

#15 Rota de listar todos os Estados
  postman-collections/Estado.postman_collection.json
Labels: melhoria

#17 Criado Arquivo ErrosDict.py
  smartcare-compose/apis/web-api/ErrorsDict.py
  smartcare-compose/apis/web-api/web-api.py
Labels: enhancement

#18 Alterado o nome da classe ErrorsDict para Get
  smartcare-compose/apis/web-api/ErrorsDict.py
  smartcare-compose/apis/web-api/web-api.py
Labels: enhancement

#19 Criada Lib ListHandling
  smartcare-compose/apis/web-api/ListHandling.py
  smartcare-compose/apis/web-api/web-api.py
  smartcare-compose/web/nginx/default.conf
Labels: enhancement, bugfix
